import java.util.ArrayList;
import java.util.Collections;

/* Generated By:JJTree: Do not edit this line. ASTARGUMENT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENT extends SimpleNode {
  protected String type;
  protected String argName;

  public ASTARGUMENT(int id) {
    super(id);
  }

  public ASTARGUMENT(Parser p, int id) {
    super(p, id);
  }

  @Override
  public ArrayList<String> getUses() {
    return new ArrayList<>(Collections.singleton(argName));
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    ASTTYPE firstChild = (ASTTYPE) this.jjtGetChild(0);
    ASTIDENT secondChild = (ASTIDENT) this.jjtGetChild(1);

    firstChild.addSymbolTable(this.symbolTable);
    firstChild.eval(analysis);

    secondChild.addSymbolTable(this.symbolTable);
    secondChild.eval(analysis);

    argName = secondChild.name;

    Symbol symbol;

    if(firstChild.typeID.equals(ControlVars.ARRAY))
      symbol = new ArraySymbol(ControlVars.INT);
    else
      symbol = new Symbol(firstChild.typeID);

    symbol.incInitialized();

    this.type = symbol.getType();

    this.symbolTable.addSymbol(argName, symbol);
  }
}
/* JavaCC - OriginalChecksum=1c4e5b4ef5eeb3f2188100031b20d30d (do not edit this line) */
