/* Generated By:JJTree: Do not edit this line. ASTARGUMENT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENT extends SimpleNode {
  protected TypeEnum type;

  public ASTARGUMENT(int id) {
    super(id);
  }

  public ASTARGUMENT(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws Exception {
    ASTTYPE firstChild = (ASTTYPE) this.jjtGetChild(0);
    ASTIDENT secondChild = (ASTIDENT) this.jjtGetChild(1);

    firstChild.addSymbolTable(this.symbolTable);
    firstChild.eval();

    secondChild.addSymbolTable(this.symbolTable);
    secondChild.eval();

    Symbol symbol = new Symbol(firstChild.typeID);

    symbol.setInitialized(true);

    this.symbolTable.addSymbol(secondChild.name, symbol);
  }
}
/* JavaCC - OriginalChecksum=1c4e5b4ef5eeb3f2188100031b20d30d (do not edit this line) */
