/* Generated By:JJTree: Do not edit this line. ASTASSIGN.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGN extends Operator {
  public ASTASSIGN(int id) {
    super(id);
  }

  public ASTASSIGN(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval(SemanticErrors errors){
    SimpleNode firstChild = (SimpleNode) this.jjtGetChild(0);
    SimpleNode secondChild = (SimpleNode) this.jjtGetChild(1);

    String varName;
    TypeEnum compatibleType;

    if(firstChild.id == ParserTreeConstants.JJTARRAY_ACCESS){
      firstChild.addSymbolTable(this.symbolTable);
      firstChild.eval(errors);
      varName = ((ASTARRAY_ACCESS) firstChild).object;
    }
    else
      varName = ((ASTIDENT) firstChild).name;

    System.out.println("Var: " + varName);

    if(!this.symbolTable.existsSymbol(varName)){

      if(!this.symbolTable.existsSymbol("this." + varName)){
        errors.addError(this.getCoords(), "Trying to assign variable " + varName + " that wasn't previously declared.");
        return;
      }

      varName = "this." + varName;
    }

    if(firstChild.id == ParserTreeConstants.JJTARRAY_ACCESS)
      compatibleType = ((ArraySymbol) this.symbolTable.getSymbol(varName)).getReturnType();
    else
      compatibleType = this.symbolTable.getSymbol(varName).getType();

    secondChild.addSymbolTable(this.symbolTable);
    secondChild.eval(errors);

    if(!this.validType(secondChild, compatibleType, errors))
      errors.addError(this.getCoords(), "Assignment of variable " + varName + " to incompatible type.");

    this.initializedUse(secondChild, errors);

    this.symbolTable.setInitialized(varName);
  }
}
/* JavaCC - OriginalChecksum=cbade18a4c362fe9b5729b12bfc068fc (do not edit this line) */
