import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

/* Generated By:JJTree: Do not edit this line. ASTASSIGN.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGN extends TypeSensitive {
  protected ArrayList<String> scopeStack = null;
  protected String definition = null;

  public ASTASSIGN(int id) {
    super(id);
  }

  public ASTASSIGN(Parser p, int id) {
    super(p, id);
  }

  @Override
  public ArrayList<String> getUses() {
    SimpleNode firstChild = (SimpleNode) this.jjtGetChild(0);
    SimpleNode secondChild = (SimpleNode) this.jjtGetChild(1);

    Set<String> uses = new HashSet<>(secondChild.getUses());

    if(firstChild.equalsNodeType(ParserTreeConstants.JJTARRAY_ACCESS)){
      ArrayList<String> accessUses = firstChild.getUses();
      accessUses.remove(definition);
      uses.addAll(accessUses);
    }

    uses.removeIf(var -> !this.symbolTable.existsSymbol(var));

    return new ArrayList<>(uses);
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    SimpleNode firstChild = (SimpleNode) this.jjtGetChild(0);
    SimpleNode secondChild = (SimpleNode) this.jjtGetChild(1);

    String varName;
    String compatibleType;

    firstChild.addSymbolTable(this.symbolTable);
    secondChild.addSymbolTable(this.symbolTable);

    if(compareNode(firstChild, ParserTreeConstants.JJTARRAY_ACCESS)){
      firstChild.eval(analysis);
      varName = ((ASTARRAY_ACCESS) firstChild).object;
    }
    else
      varName = ((ASTIDENT) firstChild).name;

    if(!this.symbolTable.existsSymbol(varName)){

      if(!this.symbolTable.existsSymbol("this." + varName) ){
        if(varName != null)
          analysis.addError(this.getCoords(), "Trying to assign variable " + varName + " that wasn't previously declared.");

        return;
      }

      if(varName != null){
        varName = "this." + varName;
      }
    } else {
      definition = varName;
    }

    if(compareNode(firstChild, ParserTreeConstants.JJTARRAY_ACCESS))
      compatibleType = ((ArraySymbol) this.symbolTable.getSymbol(varName)).getReturnType();
    else
      compatibleType = this.symbolTable.getSymbol(varName).getType();

    secondChild.eval(analysis);

    if(!this.validType(secondChild, compatibleType, analysis)){
      if(varName != null)
        analysis.addError(this.getCoords(), "Assignment of variable " + varName + " to incompatible type.");
    }

    this.initializedUse(secondChild, analysis);

    if(scopeStack != null && !scopeStack.contains(varName)){
      this.symbolTable.setInitialized(varName);
      this.scopeStack.add(varName);
    } else if (scopeStack == null && !this.symbolTable.getSymbol(varName).isInitialized())
      this.symbolTable.setInitialized(varName);

  }
}
/* JavaCC - OriginalChecksum=cbade18a4c362fe9b5729b12bfc068fc (do not edit this line) */
