/* Generated By:JJTree: Do not edit this line. ASTARGUMENTS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENTS extends SimpleNode {
  public ASTARGUMENTS(int id) {
    super(id);
  }

  public ASTARGUMENTS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4206cf5195297e62078a7d896983dc2e (do not edit this line) */
