/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADD extends SimpleNode {
  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4240bbc69b92e6c5c083af45168f306 (do not edit this line) */
