/* Generated By:JJTree: Do not edit this line. ASTBOOL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOL extends SimpleNode {

  boolean truth_value;

  public ASTBOOL(int id) {
    super(id);
  }

  public ASTBOOL(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "BOOL[" + truth_value + "]";
  }
}
/* JavaCC - OriginalChecksum=23b80ea0b958bf2b20d4453c33c247cc (do not edit this line) */
