import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTCALL.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL extends TypeSensitive {
  protected String method;
  protected ArrayList<TypeEnum> arguments = new ArrayList<>();

  public ASTCALL(int id) {
    super(id);
  }

  public ASTCALL(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    int numChildren = this.jjtGetNumChildren();

    SimpleNode firstChild = (SimpleNode) this.jjtGetChild(0);

    if(firstChild.id != ParserTreeConstants.JJTIDENT)
      analysis.addError(this.getCoords(), "First child of CALL must be an IDENT.");

    this.method = ((ASTIDENT) firstChild).name;

    if(numChildren == 1)
      return;

    SimpleNode secondChild = (SimpleNode) this.jjtGetChild(1);

    if(secondChild.id != ParserTreeConstants.JJTARGUMENTS)
      analysis.addError(this.getCoords(), "Second child of CALL must be ARGUMENTS.");

    secondChild.addSymbolTable(this.symbolTable);
    secondChild.eval(analysis);

    this.arguments = ((ASTARGUMENTS) secondChild).arguments;
  }
}
/* JavaCC - OriginalChecksum=3c6f955e59ab927fd02fc4b260500e9b (do not edit this line) */
