/* Generated By:JJTree: Do not edit this line. ASTCALL.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL extends SimpleNode {
  public ASTCALL(int id) {
    super(id);
  }

  public ASTCALL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c6f955e59ab927fd02fc4b260500e9b (do not edit this line) */
