/* Generated By:JJTree: Do not edit this line. ASTCONDITION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCONDITION extends SimpleNode {
  public ASTCONDITION(int id) {
    super(id);
  }

  public ASTCONDITION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58fa4c516c1f33d07663e796cee56418 (do not edit this line) */
