/* Generated By:JJTree: Do not edit this line. ASTDIV.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIV extends SimpleNode {
  public ASTDIV(int id) {
    super(id);
  }

  public ASTDIV(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c66fef492265519258f8aeb8df13d5f (do not edit this line) */
