/* Generated By:JJTree: Do not edit this line. ASTEXTENDS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXTENDS extends SimpleNode {
  public String extendedClass;

  public ASTEXTENDS(int id) {
    super(id);
  }

  public ASTEXTENDS(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    ASTIDENT firstChild = (ASTIDENT) this.jjtGetChild(0);

    extendedClass = firstChild.name;

    if(!this.symbolTable.existsClassSymbol(extendedClass))
      analysis.addError(this.getCoords(), "Extending class " + extendedClass + " that wasn't previously imported.");
  }
}
/* JavaCC - OriginalChecksum=cf18fd1f3efb0740e47c2bdf53bca72e (do not edit this line) */
