import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/* Generated By:JJTree: Do not edit this line. ASTIF_ELSE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_ELSE extends SimpleNode {
  protected ArrayList<String> localStack = new ArrayList<>();

  public ASTIF_ELSE(int id) {
    super(id);
  }

  public ASTIF_ELSE(Parser p, int id) {
    super(p, id);
  }

  public ArrayList<String> getDuplicates(){
    ArrayList<String> stack = new ArrayList<>();
    HashSet<String> unique = new HashSet<>();

    for (String s : this.localStack){
      if(!unique.add(s))
        stack.add(s);
    }

    unique.clear();

    return stack;
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    ASTIF firstChild = (ASTIF) this.jjtGetChild(0);
    ASTELSE secondChild = (ASTELSE) this.jjtGetChild(1);

    firstChild.addSymbolTable(this.symbolTable);
    firstChild.eval(analysis);

    localStack.addAll(firstChild.localStack);

    secondChild.addSymbolTable(this.symbolTable);
    secondChild.eval(analysis);

    localStack.addAll(secondChild.localStack);

    ArrayList<String> stack = this.getDuplicates();

    Set<String> auxSet = new HashSet<>(this.localStack);
    localStack.clear();
    localStack.addAll(auxSet);

    if(ControlVars.ANALYSE_SCOPE_VAR_INIT)
      this.symbolTable.clearInitialized(this.localStack);

    this.localStack = stack;
  }
}
/* JavaCC - OriginalChecksum=d6ae377bef4cc1fafd01d6843e24e640 (do not edit this line) */
