/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER_STATEMENT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIDENTIFIER_STATEMENT extends SimpleNode {
  public ASTIDENTIFIER_STATEMENT(int id) {
    super(id);
  }

  public ASTIDENTIFIER_STATEMENT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a98015e477b0883af4674b80ff3b3a6 (do not edit this line) */
