/* Generated By:JJTree: Do not edit this line. ASTLENGTH.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLENGTH extends Operator {
  protected String object;

  public ASTLENGTH(int id) {
    super(id);
  }

  public ASTLENGTH(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval(SemanticErrors errors){
      SimpleNode childNode = (SimpleNode) this.jjtGetChild(0);

      childNode.addSymbolTable(this.symbolTable);
      childNode.eval(errors);

      // TODO: Check if only these types can be sized!
      if(!this.validType(childNode, TypeEnum.OBJECT, errors) && !this.validType(childNode, TypeEnum.ARRAY, errors) && !this.validType(childNode, TypeEnum.STRING, errors))
          errors.addError(this.getCoords(), "Length method isn't applied to a sizable object.");
    }
  }
/* JavaCC - OriginalChecksum=9340b1c9d0f3a7601be1ff8cdf1361a0 (do not edit this line) */
