import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTLENGTH.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLENGTH extends TypeSensitive {
  protected String object;

  public ASTLENGTH(int id) {
    super(id);
  }

  public ASTLENGTH(Parser p, int id) {
    super(p, id);
  }

    @Override
    public ArrayList<String> getUses() {
        SimpleNode child = (SimpleNode) this.jjtGetChild(0);

        return child.getUses();
    }

  @Override
  public void eval(SemanticAnalysis analysis){
      SimpleNode childNode = (SimpleNode) this.jjtGetChild(0);

      childNode.addSymbolTable(this.symbolTable);
      childNode.eval(analysis);

      if(!this.validType(childNode, ControlVars.ARRAY, analysis) && !this.validType(childNode, ControlVars.STRING, analysis))
          analysis.addError(this.getCoords(), "Length method isn't applied to a sizable object.");
    }
  }
/* JavaCC - OriginalChecksum=9340b1c9d0f3a7601be1ff8cdf1361a0 (do not edit this line) */
