/* Generated By:JJTree: Do not edit this line. ASTMAINMETHOD.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMAINMETHOD extends SimpleNode {
  public ASTMAINMETHOD(int id) {
    super(id);
  }

  public ASTMAINMETHOD(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=929a511142c3eb4332a56f5c02fad9ec (do not edit this line) */
