/* Generated By:JJTree: Do not edit this line. ASTMUL.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMUL extends SimpleNode {
  public ASTMUL(int id) {
    super(id);
  }

  public ASTMUL(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9d32d9eced931fe3abd638eec2fd617 (do not edit this line) */
