/* Generated By:JJTree: Do not edit this line. ASTNEGATION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEGATION extends SimpleNode {
  public ASTNEGATION(int id) {
    super(id);
  }

  public ASTNEGATION(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ffa54cb323c32b97a8d1dfeae6338b8 (do not edit this line) */
