/* Generated By:JJTree: Do not edit this line. ASTNEW_ARRAY.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW_ARRAY extends SimpleNode {
  public ASTNEW_ARRAY(int id) {
    super(id);
  }

  public ASTNEW_ARRAY(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b8f02a40100dbc10f6cbbb183dccada (do not edit this line) */
