/* Generated By:JJTree: Do not edit this line. ASTPROGRAM.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPROGRAM extends SimpleNode {
  public ASTPROGRAM(int id) {
    super(id);
  }

  public ASTPROGRAM(Parser p, int id) {
    super(p, id);
  }

  public void eval(SemanticErrors errors){
    int numChildren = this.jjtGetNumChildren();
    int childIndex = 0;
    this.symbolTable = new SymbolTable();

    while(childIndex < numChildren){

      SimpleNode childNode = (SimpleNode) this.jjtGetChild(childIndex);

      childNode.addSymbolTable(this.symbolTable);
      childNode.eval(errors);

      childIndex++;
    }
  }
}
/* JavaCC - OriginalChecksum=fb62aa3cbadf82160503f7f40a1a01c9 (do not edit this line) */
