/* Generated By:JJTree: Do not edit this line. ASTPROGRAM.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPROGRAM extends SimpleNode {
  public ASTPROGRAM(int id) {
    super(id);
  }

  public ASTPROGRAM(Parser p, int id) {
    super(p, id);
  }

  public void eval() throws Exception {
    int numChildren = this.jjtGetNumChildren();
    int childIndex = 0;
    boolean importsDone = false;

    while(childIndex < numChildren){

      if(importsDone)
        throw new Exception("More nodes after class declaration.");

      SimpleNode childNode = (SimpleNode) this.jjtGetChild(childIndex);

      if(childNode.id == ParserTreeConstants.JJTCLASS){
        importsDone = true;
      } else if (!(childNode.id == ParserTreeConstants.JJTIMPORT || childNode.id == ParserTreeConstants.JJTSTATIC_IMPORT)){
        throw new Exception("PROGRAM got an unexpected node as child.");
      }

      childNode.addSymbolTable(this.symbolTable);
      childNode.eval();

      childIndex++;
    }
  }
}
/* JavaCC - OriginalChecksum=fb62aa3cbadf82160503f7f40a1a01c9 (do not edit this line) */
