/* Generated By:JJTree: Do not edit this line. ASTRETURN.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRETURN extends SimpleNode {
  public ASTRETURN(int id) {
    super(id);
  }

  public ASTRETURN(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws Exception {
    int numChildren = this.jjtGetNumChildren();

    if(numChildren != 1)
      throw new Exception("RETURN has more than one child.");

    SimpleNode childNode = (SimpleNode) this.jjtGetChild(0);

    if(childNode.id != ParserTreeConstants.JJTTYPE)
      throw new Exception("RETURN has child of type not TYPE.");

    TypeEnum type = ((ASTTYPE) childNode).typeID;

    // TODO: Return type?
  }

}
/* JavaCC - OriginalChecksum=cbb0390d4299ac5f8d468f97868a53a4 (do not edit this line) */
