/* Generated By:JJTree: Do not edit this line. ASTRETURN_TYPE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRETURN_TYPE extends SimpleNode {
  public ASTRETURN_TYPE(int id) {
    super(id);
  }

  public ASTRETURN_TYPE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d78c5c45d830aab60547f0ab5f54ba4f (do not edit this line) */
