/* Generated By:JJTree: Do not edit this line. ASTRETURN_TYPE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRETURN_TYPE extends SimpleNode {
  public ASTRETURN_TYPE(int id) {
    super(id);
  }

  public ASTRETURN_TYPE(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void addSymbolTable(SymbolTable symbolTable){
    this.symbolTable = symbolTable;
  }

  @Override
  public void eval() throws Exception {
    // TODO: Add symbol

    int numChildren = this.jjtGetNumChildren();

    if(numChildren != 1)
      throw new Exception("RETURN_TYPE has more than one child.");

    SimpleNode childNode = (SimpleNode) this.jjtGetChild(0);

    if(childNode.id != ParserTreeConstants.JJTTYPE)
      throw new Exception("RETURN_TYPE has child of type not TYPE.");

    childNode.addSymbolTable(this.symbolTable);
    childNode.eval();
  }
}
/* JavaCC - OriginalChecksum=d78c5c45d830aab60547f0ab5f54ba4f (do not edit this line) */
