/* Generated By:JJTree: Do not edit this line. ASTSCOPE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSCOPE extends SimpleNode {
  protected boolean unstableScope = false;
  protected boolean elseScope = false;

  public ASTSCOPE(int id) {
    super(id);
  }

  public ASTSCOPE(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    int numChildren = this.jjtGetNumChildren();
    int childIndex = 0;
    SimpleNode childNode;

    while(childIndex < numChildren){
      childNode = (SimpleNode) this.jjtGetChild(childIndex);

      if(unstableScope && childNode.id == ParserTreeConstants.JJTASSIGN){
        ((ASTASSIGN) childNode).unstableVar = true;
        ((ASTASSIGN) childNode).elseScope = this.elseScope;
      }

      childNode.addSymbolTable(this.symbolTable);
      childNode.eval(analysis);

      childIndex++;
    }
  }
}
/* JavaCC - OriginalChecksum=3a5f0f41a53986f6a6fb7874b1e64952 (do not edit this line) */
