import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTSTATIC_IMPORT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATIC_IMPORT extends SimpleNode {

  public ASTSTATIC_IMPORT(int id) {
    super(id);
  }

  public ASTSTATIC_IMPORT(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws Exception {
    int numChildren = this.jjtGetNumChildren();

    ASTIDENT firstChild = (ASTIDENT) this.jjtGetChild(0);
    ASTIDENT secondChild = (ASTIDENT) this.jjtGetChild(1);

    String key = firstChild.name + '.' + secondChild.name;

    TypeEnum returnType = TypeEnum.VOID;
    ArrayList<TypeEnum> parameters = new ArrayList<>();

    if(numChildren > 2) {
      SimpleNode thirdChild = (SimpleNode) this.jjtGetChild(2);
      thirdChild.addSymbolTable(this.symbolTable);
      thirdChild.eval();

      if (thirdChild.id == ParserTreeConstants.JJTRETURN)
        returnType = ((ASTRETURN) thirdChild).type;
      else
        parameters = ((ASTPARAMETERS) thirdChild).parameters;

      if (numChildren == 4) {
        ASTRETURN fourthChild = (ASTRETURN) this.jjtGetChild(3);
        fourthChild.addSymbolTable(this.symbolTable);
        fourthChild.eval();
        returnType = fourthChild.type;
      }
    }

    this.symbolTable.addSymbol(key, new MethodSymbol(returnType, parameters));
  }
}
/* JavaCC - OriginalChecksum=0ea55270eb33c3d4cca7df9ddcbc14ab (do not edit this line) */
