/* Generated By:JJTree: Do not edit this line. ASTSTATIC_IMPORT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATIC_IMPORT extends SimpleNode {
  public String name;

  public ASTSTATIC_IMPORT(int id) {
    super(id);
  }

  public ASTSTATIC_IMPORT(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "STATIC_IMPORT[" + name + "]";
  }
}
/* JavaCC - OriginalChecksum=0ea55270eb33c3d4cca7df9ddcbc14ab (do not edit this line) */
