/* Generated By:JJTree: Do not edit this line. ASTSTATIC_IMPORT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATIC_IMPORT extends SimpleNode {

  public ASTSTATIC_IMPORT(int id) {
    super(id);
  }

  public ASTSTATIC_IMPORT(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void addSymbolTable(SymbolTable symbolTable){
    this.symbolTable = symbolTable;
  }

  @Override
  public void eval() throws Exception {
    // TODO: Add symbol

    int numChildren = this.jjtGetNumChildren();

    if(numChildren != 2)
      throw new Exception("Static import has an irregular amount number of children nodes.");

    SimpleNode firstChild = (SimpleNode) this.jjtGetChild(0);
    SimpleNode secondChild = (SimpleNode) this.jjtGetChild(1);

    if(firstChild.id == ParserTreeConstants.JJTPARAMETERS){
      firstChild.addSymbolTable(this.symbolTable);
      firstChild.eval();
    } else {
      throw new Exception("Static import doesn't have the parameters node in the correct place or at all.");
    }

    if(secondChild.id == ParserTreeConstants.JJTRETURN){
      secondChild.addSymbolTable(this.symbolTable);
      secondChild.eval();
    } else {
      throw new Exception("Static import doesn't have the return node in the correct place or at all.");
    }
  }

  public String toString() {
    return "STATIC_IMPORT";
  }
}
/* JavaCC - OriginalChecksum=0ea55270eb33c3d4cca7df9ddcbc14ab (do not edit this line) */
