/* Generated By:JJTree: Do not edit this line. ASTVARIABLE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVARIABLE extends SimpleNode {
  protected boolean classScope = false;
  protected String name = null;

  public ASTVARIABLE(int id) {
    super(id);
  }

  public ASTVARIABLE(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval(SemanticAnalysis analysis){
    SimpleNode firstChild = (SimpleNode) this.jjtGetChild(0);
    ASTIDENT secondChild = (ASTIDENT) this.jjtGetChild(1);

    TypeEnum type;

    if(compareNode(firstChild, ParserTreeConstants.JJTIDENT)){
      name = ((ASTIDENT) firstChild).name;

      Symbol symbol = this.symbolTable.getSymbol(name);

      if(symbol == null){
        analysis.addError(this.getCoords(), "Unrecognized type " + name + ".");
        return;
      }

      type = symbol.getType();
    } else {
      firstChild.addSymbolTable(this.symbolTable);
      firstChild.eval(analysis);

      type = ((ASTTYPE) firstChild).typeID;
      name = ((ASTTYPE) firstChild).varName;
    }

    String key = (classScope ? "this." : "") + secondChild.name;

    if(this.symbolTable.existsSymbol(key)){
      analysis.addError(this.getCoords(), "Variable " + key + " already declared.");
      return;
    }

    Symbol symbol;

    if(type == TypeEnum.ARRAY){
      symbol = new ArraySymbol(TypeEnum.INT);

      if(classScope)
        symbol.incInitialized();

      this.symbolTable.addSymbol(key, symbol);
    }
    else if(type == TypeEnum.OBJECT){
      symbol = new Symbol(type, name);

      if(classScope)
        symbol.incInitialized();

      this.symbolTable.addSymbol(key, symbol);
    }
    else{
      symbol = new Symbol(type);

      if(classScope)
        symbol.incInitialized();

      this.symbolTable.addSymbol(key, symbol);
    }
  }
}
/* JavaCC - OriginalChecksum=f4f029f02b50c27d11f0009ca087d42c (do not edit this line) */
