/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.1_2 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTPARAMETERS = 2;
  public int JJTRETURN = 3;
  public int JJTSTATIC_IMPORT = 4;
  public int JJTIMPORT = 5;
  public int JJTCLASS = 6;
  public int JJTEXTENDS = 7;
  public int JJTVARIABLE = 8;
  public int JJTTYPE = 9;
  public int JJTMETHOD = 10;
  public int JJTMETHOD_BODY = 11;
  public int JJTRETURN_EXP = 12;
  public int JJTARGUMENTS = 13;
  public int JJTARGUMENT = 14;
  public int JJTMAINMETHOD = 15;
  public int JJTSCOPE = 16;
  public int JJTIF_ELSE = 17;
  public int JJTIF = 18;
  public int JJTELSE = 19;
  public int JJTWHILE = 20;
  public int JJTCONDITION = 21;
  public int JJTARRAY_ACCESS = 22;
  public int JJTASSIGN = 23;
  public int JJTAND = 24;
  public int JJTLESSTHAN = 25;
  public int JJTADD = 26;
  public int JJTSUB = 27;
  public int JJTMUL = 28;
  public int JJTDIV = 29;
  public int JJTLENGTH = 30;
  public int JJTFUNC_METHOD = 31;
  public int JJTCALL = 32;
  public int JJTNUM = 33;
  public int JJTBOOL = 34;
  public int JJTTHIS = 35;
  public int JJTNEW_ARRAY = 36;
  public int JJTNEW = 37;
  public int JJTNEGATION = 38;
  public int JJTIDENT = 39;


  public String[] jjtNodeName = {
    "PROGRAM",
    "void",
    "PARAMETERS",
    "RETURN",
    "STATIC_IMPORT",
    "IMPORT",
    "CLASS",
    "EXTENDS",
    "VARIABLE",
    "TYPE",
    "METHOD",
    "METHOD_BODY",
    "RETURN_EXP",
    "ARGUMENTS",
    "ARGUMENT",
    "MAINMETHOD",
    "SCOPE",
    "IF_ELSE",
    "IF",
    "ELSE",
    "WHILE",
    "CONDITION",
    "ARRAY_ACCESS",
    "ASSIGN",
    "AND",
    "LESSTHAN",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "LENGTH",
    "FUNC_METHOD",
    "CALL",
    "NUM",
    "BOOL",
    "THIS",
    "NEW_ARRAY",
    "NEW",
    "NEGATION",
    "IDENT",
  };
}
/* JavaCC - OriginalChecksum=e301c6a182e5c2e47ef696517272164c (do not edit this line) */
