/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.1_2 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTPARAMETERS = 2;
  public int JJTRETURN = 3;
  public int JJTSTATIC_IMPORT = 4;
  public int JJTIMPORT = 5;
  public int JJTCLASS = 6;
  public int JJTEXTENDS = 7;
  public int JJTVARIABLE = 8;
  public int JJTIDENT = 9;
  public int JJTTYPE = 10;
  public int JJTMETHOD = 11;
  public int JJTRETURN_TYPE = 12;
  public int JJTMETHOD_BODY = 13;
  public int JJTARGUMENTS = 14;
  public int JJTMAINMETHOD = 15;
  public int JJTSCOPE = 16;
  public int JJTIF = 17;
  public int JJTELSE = 18;
  public int JJTWHILE = 19;
  public int JJTCONDITION = 20;
  public int JJTARRAY_ACCESS = 21;
  public int JJTASSIGN = 22;
  public int JJTAND = 23;
  public int JJTLESSTHAN = 24;
  public int JJTADD = 25;
  public int JJTSUB = 26;
  public int JJTMUL = 27;
  public int JJTDIV = 28;
  public int JJTFUNC_METHOD = 29;
  public int JJTLENGTH = 30;
  public int JJTNUM = 31;
  public int JJTBOOL = 32;
  public int JJTTHIS = 33;
  public int JJTNEW = 34;
  public int JJTNEGATION = 35;
  public int JJTARGUMENT = 36;


  public String[] jjtNodeName = {
    "PROGRAM",
    "void",
    "PARAMETERS",
    "RETURN",
    "STATIC_IMPORT",
    "IMPORT",
    "CLASS",
    "EXTENDS",
    "VARIABLE",
    "IDENT",
    "TYPE",
    "METHOD",
    "RETURN_TYPE",
    "METHOD_BODY",
    "ARGUMENTS",
    "MAINMETHOD",
    "SCOPE",
    "IF",
    "ELSE",
    "WHILE",
    "CONDITION",
    "ARRAY_ACCESS",
    "ASSIGN",
    "AND",
    "LESSTHAN",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "FUNC_METHOD",
    "LENGTH",
    "NUM",
    "BOOL",
    "THIS",
    "NEW",
    "NEGATION",
    "ARGUMENT",
  };
}
/* JavaCC - OriginalChecksum=6335d83c9b216a858727641f9f14327a (do not edit this line) */
