/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

  private SourceCoords myCoords;

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Parser parser;
  protected SymbolTable symbolTable;

  protected boolean compareNode(SimpleNode node, int type){
    return node.id == type;
  }

  protected void setMethodThis(){
    SimpleNode parent = (SimpleNode) this.jjtGetParent();

    if(parent == null)
      return;

    if(parent.equalsNodeType(ParserTreeConstants.JJTMETHOD))
      ((ASTMETHOD) parent).thisRequired = true;
    else
      parent.setMethodThis();
  }

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(Parser p, int i) {
    this(i);
    parser = p;
  }

  public void setCoords( SourceCoords toSet ) { myCoords = toSet ; }
  public SourceCoords getCoords() { return myCoords ; }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public boolean equalsNodeType(int nodeType){ return this.id == nodeType; }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public Node[] jjtGetChildren() {
    return children;
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() {
    return ParserTreeConstants.jjtNodeName[id];
  }
  public String toString(String prefix) { return prefix + toString(); }

  public void addSymbolTable(SymbolTable symbolTable){
    this.symbolTable = symbolTable;
  }

  public void eval(SemanticAnalysis analysis) {
  }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "   ");
        }
      }
    }
  }

  public int getId() {
    return id;
  }

  String getJasmin() {
    return "";
  }


}


/* JavaCC - OriginalChecksum=ff562ba524f63263971357127128f566 (do not edit this line) */
