/* Generated By:JJTree: Do not edit this line. ASTAssignComplexExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignComplexExpression extends SimpleNode {
  public ASTAssignComplexExpression(int id) {
    super(id);
  }

  public ASTAssignComplexExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2566b4cda2cfaf3c30e7db2f4928b16d (do not edit this line) */
