/* Generated By:JJTree: Do not edit this line. ASTAccessComplexExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessComplexExpression extends SimpleNode {
  public ASTAccessComplexExpression(int id) {
    super(id);
  }

  public ASTAccessComplexExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27c5f5fcb87e6f7e2178764135f3445e (do not edit this line) */
