/* Generated By:JJTree: Do not edit this line. ASTAssignStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignStatement extends SimpleNode {
  public ASTAssignStatement(int id) {
    super(id);
  }

  public ASTAssignStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de07624a12d717bbe66699bf215f845a (do not edit this line) */
