/* Generated By:JJTree: Do not edit this line. ASTComplete.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComplete extends SimpleNode {
  public ASTComplete(int id) {
    super(id);
  }

  public ASTComplete(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=831782ffa5a7ae28cf23fe472fa339f5 (do not edit this line) */
