/* Generated By:JJTree: Do not edit this line. ASTComplexExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComplexExpression extends SimpleNode {
  public ASTComplexExpression(int id) {
    super(id);
  }

  public ASTComplexExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=145f0f70da206a72d68f452072019942 (do not edit this line) */
