/* Generated By:JJTree: Do not edit this line. ASTEnclosedStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEnclosedStatement extends SimpleNode {
  public ASTEnclosedStatement(int id) {
    super(id);
  }

  public ASTEnclosedStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42af72c1001e587573b61406f5d1114c (do not edit this line) */
