/* Generated By:JJTree: Do not edit this line. ASTIdentifierStatements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifierStatements extends SimpleNode {
  public ASTIdentifierStatements(int id) {
    super(id);
  }

  public ASTIdentifierStatements(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d835ccc9a1066eb1c2c14487b4dfc290 (do not edit this line) */
