/* Generated By:JJTree: Do not edit this line. ASTIdentifierVarDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifierVarDeclaration extends SimpleNode {
  public ASTIdentifierVarDeclaration(int id) {
    super(id);
  }

  public ASTIdentifierVarDeclaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c91adf2eb2cbe89ee71eb982fbfe350d (do not edit this line) */
