/* Generated By:JJTree: Do not edit this line. ASTITerminalExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTITerminalExpression extends SimpleNode {
  public ASTITerminalExpression(int id) {
    super(id);
  }

  public ASTITerminalExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d942d0eaebce7dde120f6517d5dd37d (do not edit this line) */
