/* Generated By:JJTree: Do not edit this line. ASTLESSTHAN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESSTHAN extends SimpleNode {
  public ASTLESSTHAN(int id) {
    super(id);
  }

  public ASTLESSTHAN(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0c17f3f22ffe1fc75eec64193a74e7f (do not edit this line) */
