/* Generated By:JJTree: Do not edit this line. ASTMULT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMULT extends SimpleNode {
  public ASTMULT(int id) {
    super(id);
  }

  public ASTMULT(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4cbac0aebd9ba64357773186e41cd7cd (do not edit this line) */
