/* Generated By:JJTree: Do not edit this line. ASTMainMethod.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethod extends SimpleNode {
  public ASTMainMethod(int id) {
    super(id);
  }

  public ASTMainMethod(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=215ea81f8e3a8a28a25be61b5ef5bf9b (do not edit this line) */
