/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodBody extends SimpleNode {
  public ASTMethodBody(int id) {
    super(id);
  }

  public ASTMethodBody(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a38a4d1d0212b5d6e857ffd7a449aeb (do not edit this line) */
