/* Generated By:JJTree: Do not edit this line. ASTNoAccessComplexExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNoAccessComplexExpression extends SimpleNode {
  public ASTNoAccessComplexExpression(int id) {
    super(id);
  }

  public ASTNoAccessComplexExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac15903adefcfec0088494f9093b27e2 (do not edit this line) */
