/* Generated By:JJTree: Do not edit this line. ASTNonIdentifierType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNonIdentifierType extends SimpleNode {
  public ASTNonIdentifierType(int id) {
    super(id);
  }

  public ASTNonIdentifierType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e19251bae3e5160f30a568f46687542 (do not edit this line) */
