/* Generated By:JJTree: Do not edit this line. ASTNITerminalExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNITerminalExpression extends SimpleNode {
  public ASTNITerminalExpression(int id) {
    super(id);
  }

  public ASTNITerminalExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3d440b4e64d3066feaf6bd5a7bc59c2 (do not edit this line) */
