/* Generated By:JJTree: Do not edit this line. ASTNonIdentifierVarDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNonIdentifierVarDeclaration extends SimpleNode {
  public ASTNonIdentifierVarDeclaration(int id) {
    super(id);
  }

  public ASTNonIdentifierVarDeclaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8482ac4a1a60443c7c6ccfb08b52be9a (do not edit this line) */
