/* Generated By:JJTree: Do not edit this line. ASTNonIdentifierStatements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNonIdentifierStatements extends SimpleNode {
  public ASTNonIdentifierStatements(int id) {
    super(id);
  }

  public ASTNonIdentifierStatements(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5aded27d5aff53be43e286850dede782 (do not edit this line) */
