/* Generated By:JJTree: Do not edit this line. ASTOperationsPriority2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperationsPriority2 extends SimpleNode {
  public ASTOperationsPriority2(int id) {
    super(id);
  }

  public ASTOperationsPriority2(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc8e4c12156648be1982bc65788462ca (do not edit this line) */
