/* Generated By:JJTree: Do not edit this line. ASTOperationsPriority1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperationsPriority1 extends SimpleNode {
  public ASTOperationsPriority1(int id) {
    super(id);
  }

  public ASTOperationsPriority1(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b56c84717a451b949fe9e1cb3df776f0 (do not edit this line) */
