/* Generated By:JJTree: Do not edit this line. ASTOperationsPriority3.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperationsPriority3 extends SimpleNode {
  public ASTOperationsPriority3(int id) {
    super(id);
  }

  public ASTOperationsPriority3(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d54c4f11b2443ef159d2293d306b7a83 (do not edit this line) */
