/* Generated By:JJTree: Do not edit this line. ASTRegularMethod.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRegularMethod extends SimpleNode {
  public ASTRegularMethod(int id) {
    super(id);
  }

  public ASTRegularMethod(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c766584ecdd1ed98c9b7b3145638ec2 (do not edit this line) */
