/* Generated By:JJTree: Do not edit this line. ASTRegularStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRegularStatement extends SimpleNode {
  public ASTRegularStatement(int id) {
    super(id);
  }

  public ASTRegularStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f970228b3402269d8652f25dd26f7081 (do not edit this line) */
