/* Generated By:JJTree: Do not edit this line. ASTSUM.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSUM extends SimpleNode {
  public ASTSUM(int id) {
    super(id);
  }

  public ASTSUM(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=911292d54dff71934fc5ee9e3c4f50dd (do not edit this line) */
