/* Generated By:JJTree: Do not edit this line. ASTTerminalExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTerminalExpression extends SimpleNode {
  public ASTTerminalExpression(int id) {
    super(id);
  }

  public ASTTerminalExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c68b38d878899d3731169d26294b545f (do not edit this line) */
