/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTCOMPLETE = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTNONIDENTIFIERVARDECLARATION = 5;
  public int JJTIDENTIFIERVARDECLARATION = 6;
  public int JJTTYPE = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTREGULARMETHOD = 9;
  public int JJTMAINMETHOD = 10;
  public int JJTMETHODBODY = 11;
  public int JJTSTATEMENT = 12;
  public int JJTENCLOSEDSTATEMENT = 13;
  public int JJTIFELSESTATEMENT = 14;
  public int JJTWHILESTATEMENT = 15;
  public int JJTNONIDENTIFIERSTATEMENTS = 16;
  public int JJTIDENTIFIERSTATEMENTS = 17;
  public int JJTARRAYACCESS = 18;
  public int JJTASSIGNSTATEMENT = 19;
  public int JJTCOMPLEXEXPRESSION = 20;
  public int JJTNOACCESSCOMPLEXEXPRESSION = 21;
  public int JJTLENGTH = 22;
  public int JJTFUNCMETHOD = 23;
  public int JJTOPERATIONSPRIORITY1 = 24;
  public int JJTOPERATIONSPRIORITY2 = 25;
  public int JJTOPERATIONSPRIORITY3 = 26;
  public int JJTACCESSCOMPLEXEXPRESSION = 27;
  public int JJTTERMINALEXPRESSION = 28;
  public int JJTNITERMINALEXPRESSION = 29;
  public int JJTNUM = 30;
  public int JJTBOOL = 31;
  public int JJTITERMINALEXPRESSION = 32;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "Complete",
    "ClassDeclaration",
    "VarDeclaration",
    "NonIdentifierVarDeclaration",
    "IdentifierVarDeclaration",
    "Type",
    "MethodDeclaration",
    "RegularMethod",
    "MainMethod",
    "MethodBody",
    "Statement",
    "EnclosedStatement",
    "IfElseStatement",
    "WhileStatement",
    "NonIdentifierStatements",
    "IdentifierStatements",
    "ArrayAccess",
    "AssignStatement",
    "ComplexExpression",
    "NoAccessComplexExpression",
    "LENGTH",
    "FUNCMETHOD",
    "OperationsPriority1",
    "OperationsPriority2",
    "OperationsPriority3",
    "AccessComplexExpression",
    "TerminalExpression",
    "NITerminalExpression",
    "NUM",
    "BOOL",
    "ITerminalExpression",
  };
}
/* JavaCC - OriginalChecksum=807e82d3a58d2c986a3d6c1e1179c22c (do not edit this line) */
